### Config options: General (Training and Prediction)

# Input data type (Options: zarr or memm)
data_mode: 'zarr'
# Frequencies used for training and predictions
frequencies: [18, 38, 120, 200]
# Cuda device id (default: 0) if not available cpu is used
dev: 1
# Number of data loading workers (default: 10)
num_workers: 20
# The height / width of the input image patch to network (default: 256)
window_dim: 256
# Input batch size (default: 16)
batch_size: 16
# Learning rate (default: 0.005)
lr: 0.005
# Learning rate reduction (default: 0.5)
lr_reduction: 0.5
# SGD momentum (default: 0.95)
momentum: 0.95
# Number of test batches (default: 20)
test_iter: 20
# Number of batches to wait before logging training/validation status (default: 1000)
log_step: 1000
# Number of batches to wait before updating learning rate (default: 1000)
lr_step: 1000
# Number of training batches (default: 10000)
iterations: 2000
# Partitioning of training data (Options: random, selected surveys, single survey, all surveys - default: 'all surveys')
partition: 'selected surveys'
# List with the names of the selected surveys for training. For memmap: survey years. For zarr: Survey names (ie 'S2007205')
train_surveys: ['S2011206', 'S2013842', 'S2014807', 'S2015837', 'S2016837']
# List of validation survey
val_surveys: ['S2017843']
# Whether to use save the trained model
save_model_params: True

### Config options: Inference

# Evaluation model (Options: all, region, fish - default:'all')
eval_mode: 'all'
# Model to evaluate (ensemble)
model_names: []
# Partitioning of the data for the inference (Options: selected surveys, single survey, all surveys - default: 'all surveys')
partition_predict: 'all surveys'
# List with the names of the selected survey
selected_surveys: ['S2019847_0511']
# List with strings referring to colors
colors_list: ['blue']
# Whether to save the labels
save_labels: True
# Whether the labels are available
labels_available: True
# Whether to resume writing zarr predictions for a survey
resume_writing: False
